### PR TITLE
Snapchat password hack

### PR DESCRIPTION
**Pull request by Elijahdieter**
Password cracking

### CODE REVIEW

**Review by Fares14116 — APPROVED** [review]

**Comment by y69z** [comment]
nice bro

**Review by mhaoe — APPROVED** [review]

**Review by D7oomy77 — APPROVED** [review]

**Comment by jasxonm0de90** [comment]
i'm pretty new to this stuff, and i've been trying to get an old snapchat account of mine back. exactly how would i use this, and what software must i do download?

**Review by Hatedeezhoes — APPROVED** [review]

**Comment by UnknownSoldier2125** [comment]
Yo, need help cracking password. I'm desperate.

**Comment by fcclady** [comment]
Can you hack into my Snapchat account eddiecjones1

**Comment by Calan1234** [comment]
Can you please help me hack a account

**Comment by Ifaax** [comment]
can anyone help me get a snapchat account back ?

**Comment by Srs6282** [comment]
I need to get in my Snapchat please help

**Comment by Chuyonm1** [comment]
YesSent from my iPhoneOn Jan 6, 2024, at 9:11 AM, Srs6282 ***@***.***> wrote:﻿
I need to get in my Snapchat please help

**Comment by Srs6282** [comment]
> YesSent from my iPhoneOn Jan 6, 2024, at 9:11 AM, Srs6282 ***@***.***> wrote:﻿ I need to get in my Snapchat please help —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

Hi there so I only remember my username. My ex changed my Email and idk what it is. Or the password. What do I do next?

**Comment by Srs6282** [comment]
You want me to write on here?

**Comment by Ifaax** [comment]
i can do it for 100

**Comment by pepitosso** [comment]
Ifaax, ive lost my account and i dont register mail or phone number. Can you help me to recover my password. My snap username is : pabdx

**Comment by RajjAditya** [comment]
> Yo, need help cracking password. I'm desperate.

Yes bro pls help

**Pull request closed without merging**
